package net.buj.loader;

public class R { // Soon to become autogenerated
    private R() {}

    public static String VERSION_NAME = "1.1.0.7-dev-xxxxxx";
    public static String CLIENT_DOWNLOAD_URL = "https://github.com/AlphaVerUnofficialJars/LilypadClient/releases/download/v106/lilypad_qamod_v106.jar";
    public static String SERVER_DOWNLOAD_URL = "https://github.com/AlphaVerUnofficialJars/LilypadServer/releases/download/v105/lilypad_server_v105.jar";
}
